### ISSUE TITLE
浮点运算问题

### ISSUE THREAD

**Issue by FangXS-github** [iE-zhi/NMEA_GPS_parse#1]
您好:
       此仓库非常不错，但是如果应用在不带浮点运算或只带单精度浮点运算单元的MCU上，会造成一定程度的底运算效率和较长时间的运算，后续是否会添加宏定义配置使能或失能使用浮点数运算？
   
   期待您的回复！
   Fang XS.

**Comment by iE-zhi** [comment]
非常抱歉，刚看到，我写个程序测试下吧，这个好像只是提取参数，设计到的浮点运算并不多

**Comment by FangXS-github** [comment]
可使用此方法：可直接将浮点转换为(value, scale),例如1.23  ==>  (123, 100),这样的话，需要获取整数位直接value / scale，小数位value % scale。
类似如下结构：
struct NEMA_GPS_Float {
   int value;
   uint scale;
};

**Comment by iE-zhi** [comment]
原来是这样，之前没碰到过这需求，要是有这需求，你这方法确实不错
